package com.synapticloop.tinycms.sqlite.h2zero.inserter;

// - - - - thoughtfully generated by synapticloop h2zero - - - - 
//    with the use of synapticloop templar templating language
//              (java-create-inserter.templar)

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.math.BigDecimal;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.synapticloop.h2zero.base.manager.sqlite3.ConnectionManager;
import com.synapticloop.tinycms.sqlite.h2zero.model.util.Constants;

/**
 * This class contains the methods to insert new rows into the: 
 *   <code>tinycms.data_field</code>
 * table.  The fields that are available are as follows:
 * 
 * <ul>
 *  <li><code>id_data_field</code> (bigint)  <strong>NOT</strong> nullable  (PRIMARY)</li>
 *  <li><code>id_field</code> (bigint)  <strong>NOT</strong> nullable </li>
 * </ul>
 * 
 * @author synapticloop h2zero
 */

public class DataFieldInserter {
	// the binder is unused in code, but will generate compile problems if this 
	// class is no longer referenced in the h2zero file. Just a nicety for
	// removing dead code
	@SuppressWarnings("unused")
	private static final String BINDER = Constants.DATA_FIELD_BINDER;

		private static final Logger LOGGER = LoggerFactory.getLogger(DataFieldInserter.class);

	// static fields generated by synapticloop h2zero
	private static final String SQL_BUILTIN_INSERT_ALL = "insert into data_field(id_data_field, id_field)";
	private static final String SQL_BUILTIN_INSERT_VALUES = SQL_BUILTIN_INSERT_ALL + " values (?, ?)";
	// static inserter SQL generated from the user input

	private DataFieldInserter() {}

	/**
	 * Insert a new DataField into the database utilising the passed in connection.
	 * 
	 * @param connection the connection to use for the database, this __MUST__ be 
	 *   closed by the calling function.
	 * @param idDataField  maps to id_data_field
	 * @param idField  maps to id_field
	 * 
	 * @return the number of rows that were inserted, or -1 if an error occurred
	 * 
	 * @throws SQLException if there was an error in the SQL insert statement
	 */
	public static int insert(Connection connection, Long idDataField, Long idField) throws SQLException {
		try (PreparedStatement preparedStatement = connection.prepareStatement(SQL_BUILTIN_INSERT_VALUES)) {
			ConnectionManager.setBigint(preparedStatement, 1, idDataField);
			ConnectionManager.setBigint(preparedStatement, 2, idField);
			return(preparedStatement.executeUpdate());
		}
	}

	/**
	 * Insert a new DataField into the database a new connection will be retrieved 
	 * from the pool, used and then closed.
	 * 
	 * @param idDataField  maps to id_data_field
	 * @param idField  maps to id_field
	 * 
	 * @return the number of rows that were inserted, or -1 if an error occurred
	 * 
	 * @throws SQLException if there was an error in the SQL insert statement
	 */
	public static int insert(Long idDataField, Long idField) throws SQLException {
		try (Connection connection = ConnectionManager.getConnection()) {
			return(insert(connection, idDataField, idField));
		}
	}

	/**
	 * Silently (i.e. swallow any exceptions) Insert a new DataField into the 
	 * database utilising the passed in connection. If an exception is thrown by the
	 * method, the exception message will be logged as an 'error', if 'trace' logging
	 * is enabled, the stack trace will be printed to the output stream.
	 * 
	 * @param connection the connection to use for the database, this __MUST__ be 
	 *   closed by the calling function.
	 * @param idDataField  maps to id_data_field
	 * @param idField  maps to id_field
	 * 
	 * @return the number of rows that were inserted, or -1 if an error occurred
	 */
	public static int insertSilent(Connection connection, Long idDataField, Long idField) {
		try {
			return(insert(connection, idDataField, idField));
		} catch (SQLException sqlex) {
			LOGGER.error("SQLException caught, message was: {}", sqlex.getMessage());
			if(LOGGER.isTraceEnabled()){
				sqlex.printStackTrace();
			}
			return(-1);
		}
	}

	/**
	 * Silently (i.e. swallow any exceptions) Insert a new DataField into the 
	 * database, creating and closing a connection in the process. If an exception is thrown 
	 * by the method, the exception message will be logged as an 'error', if 'trace' logging
	 * is enabled, the stack trace will be printed to the output stream.
	 * 
	 * @param idDataField  maps to id_data_field
	 * @param idField  maps to id_field
	 * 
	 * @return the number of rows that were inserted, or -1 if an error occurred
	 */
	public static int insertSilent(Long idDataField, Long idField) {
		try (Connection connection = ConnectionManager.getConnection()){
			return(insert(connection, idDataField, idField));
		} catch (SQLException sqlex) {
			LOGGER.error("SQLException caught, message was: {}", sqlex.getMessage());
			if(LOGGER.isTraceEnabled()){
				sqlex.printStackTrace();
			}
			return(-1);
		}
	}

}