package com.synapticloop.tinycms.sqlite.h2zero.model;

// - - - - thoughtfully generated by synapticloop h2zero - - - - 
//    with the use of synapticloop templar templating language
//                  (java-create-model.templar)

import com.synapticloop.h2zero.base.manager.sqlite3.ConnectionManager;
import com.synapticloop.h2zero.base.validator.bean.ValidationBean;
import com.synapticloop.h2zero.base.validator.bean.ValidationFieldBean;
import com.synapticloop.tinycms.sqlite.h2zero.question.FieldTypeQuestion;
import com.synapticloop.tinycms.sqlite.h2zero.question.CollectionQuestion;
import com.synapticloop.h2zero.base.validator.*;
import com.synapticloop.h2zero.base.model.sqlite3.ModelBase;
import com.synapticloop.h2zero.base.exception.H2ZeroPrimaryKeyException;
import com.synapticloop.h2zero.base.exception.H2ZeroFinderException;
import java.lang.StringBuilder;
import java.sql.Connection;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import org.json.JSONObject;
import com.synapticloop.h2zero.util.XmlHelper;

import com.synapticloop.h2zero.base.model.ModelBaseHelper;
import com.synapticloop.tinycms.sqlite.h2zero.model.util.Constants;

import com.synapticloop.tinycms.sqlite.h2zero.finder.FieldFinder;
import com.synapticloop.tinycms.sqlite.h2zero.finder.CollectionFinder;


/**
 * <p>This is the model for the <code>Field</code> which maps to the <code>field</code> database table.</p>
 * <p>This class contains all CRUD (Create, Read, Update, and Delete) methods.</p>
  * 
 * @author synapticloop h2zero
 * 
 * <p>@see <a href="https://github.com/synapticloop/h2zero">Synapticloop h2zero GitHub repository</a></p>
 */
public class Field extends ModelBase {
	// the binder is unused in code, but will generate compile problems if this 
	// class is no longer referenced in the h2zero file. Just a nicety for
	// removing dead code
	@SuppressWarnings("unused")
	private static final String BINDER = Constants.FIELD_BINDER;


	public static final String PRIMARY_KEY_FIELD = "id_field";  // the primary key - a convenience field

	private static final String SQL_INSERT = 
		"""
			insert into
			field (
				id_field_type,
				id_collection,
				nm_field
			) values (
				?,
				?,
				?
			)
		""";
	private static final String SQL_UPDATE = 
		"""
			update
				field
			set
				id_field_type = ?,
				id_collection = ?,
				nm_field = ?
			where
		"""
			+ PRIMARY_KEY_FIELD + 
		"""
			= ?
		""";
	private static final String SQL_DELETE = "delete from field where " + PRIMARY_KEY_FIELD + " = ?";
	private static final String SQL_ENSURE = "select " + PRIMARY_KEY_FIELD + " from field where id_field_type = ? and id_collection = ? and nm_field = ?";


	// Static lookups for fields in the hit counter.
	// Whilst these aren't used internally (the offset to the array is 
	// automatically computer, external classes can use these static fields 
	// to look up the hit counts in the array 
	public static final int HIT_TOTAL = 0;
	public static final int HIT_ID_FIELD = 1;
	public static final int HIT_ID_FIELD_TYPE = 2;
	public static final int HIT_ID_COLLECTION = 3;
	public static final int HIT_NM_FIELD = 4;


	// the list of fields for the hit - starting with 'TOTAL'
	private static final String[] HIT_FIELDS = { "TOTAL", "id_field", "id_field_type", "id_collection", "nm_field" };
	// the number of read-hits for a particular field
	private static final int[] HIT_COUNTS = { 0, 0, 0, 0, 0 };

	private Collection Collection = null; // maps to the id_collection field

	private Long idField = null; // maps to the id_field field
	private Long idFieldType = null; // maps to the id_field_type field
	private Long idCollection = null; // maps to the id_collection field
	private String nmField = null; // maps to the nm_field field

	public Field(Long idField, Long idFieldType, Long idCollection, String nmField) {
		this.idField = idField;
		this.idFieldType = idFieldType;
		this.idCollection = idCollection;
		this.nmField = nmField;
	}

	/**
	 * <p>Get a new Field model, or set the fields on an existing
	 * Field model.</p>
	 * 
	 * <p>If the passed in field is null, then a new Field
	 * will be created.  If not null, the fields will be updated on the passed in model.</p>
	 * 
	 * <p><strong>NOTE:</strong> You will still need to persist this to the database
	 * with an <code>upsert()</code> call - this will insert the model if it .
	 * doesn't exist, or update the existing model.</p>
	 * 
	 * @param field the model to check
	 * @param idFieldType - maps to the <code>id_field_type</code> field.
	 * @param idCollection - maps to the <code>id_collection</code> field.
	 * @param nmField - maps to the <code>nm_field</code> field.
	 * 
	 * @return Either the existing field with updated field values,
	 *   or a new Field with the field values set.
	 */
	public static Field getOrSet(Field field,Long idFieldType, Long idCollection, String nmField) {
		if(null == field) {
			return (new Field(null, idFieldType, idCollection, nmField));
		} else {
			field.setIdFieldType(idFieldType);
			field.setIdCollection(idCollection);
			field.setNmField(nmField);

			return(field);
		}
	}

	@Override
	public boolean primaryKeySet() {
		return(null != idField);
	}


	@Override
	public void insert(Connection connection) throws SQLException, H2ZeroPrimaryKeyException {
		if(primaryKeySet()) {
			throw new H2ZeroPrimaryKeyException("Cannot insert field model when primary key is not null.");
		}

		PreparedStatement preparedStatement = null;
		ResultSet resultSet = null;
		try {
			// create this bean 
			preparedStatement = connection.prepareStatement(SQL_INSERT, Statement.RETURN_GENERATED_KEYS);
			ConnectionManager.setBigint(preparedStatement, 1, idFieldType);
			ConnectionManager.setBigint(preparedStatement, 2, idCollection);
			ConnectionManager.setVarchar(preparedStatement, 3, nmField);
			preparedStatement.executeUpdate();
			resultSet = preparedStatement.getGeneratedKeys();
			if(resultSet.next()) {
				this.idField = resultSet.getLong(1);
			} else {
				throw new H2ZeroPrimaryKeyException("Could not get return value for primary key!");
			}
		} finally {
			ConnectionManager.closeAll(resultSet, preparedStatement);
		}
	}

	@Override
	public void ensure(Connection connection) throws SQLException, H2ZeroPrimaryKeyException {

		PreparedStatement preparedStatement = null;
		ResultSet resultSet = null;
		try {
			preparedStatement = connection.prepareStatement(SQL_ENSURE);
			ConnectionManager.setBigint(preparedStatement, 1, idFieldType);
			ConnectionManager.setBigint(preparedStatement, 2, idCollection);
			ConnectionManager.setVarchar(preparedStatement, 3, nmField);
			resultSet = preparedStatement.executeQuery();
			if(resultSet.next()) {
				this.idField = resultSet.getLong(1);
			} else {
				// could not find the value - need to insert it - null is the primary key
				insert(connection);
			}
		} finally {
			ConnectionManager.closeAll(resultSet, preparedStatement);
		}
	}

	@Override
	public void update(Connection connection) throws SQLException, H2ZeroPrimaryKeyException {
		if(!primaryKeySet()) {
			throw new H2ZeroPrimaryKeyException("Cannot update bean when primary key is null.");
		}

		if(isDirty) {
			try (PreparedStatement preparedStatement = connection.prepareStatement(SQL_UPDATE)) {
				// update this bean, but only if dirty
				ConnectionManager.setBigint(preparedStatement, 1, idFieldType);
				ConnectionManager.setBigint(preparedStatement, 2, idCollection);
				ConnectionManager.setVarchar(preparedStatement, 3, nmField);
				// now set the primary key
				preparedStatement.setLong(4, idField);
				preparedStatement.executeUpdate();
			} finally {
				isDirty = false;
			}
		}
	}

	@Override
	public void delete(Connection connection) throws SQLException, H2ZeroPrimaryKeyException {
		if(!primaryKeySet()) {
			throw new H2ZeroPrimaryKeyException("Cannot delete bean when primary key is null.");
		}
		try (PreparedStatement preparedStatement = connection.prepareStatement(SQL_DELETE)) {
			preparedStatement.setLong(1, idField);
			preparedStatement.executeUpdate();
		}
	}

	@Override
	public void refresh(Connection connection) throws SQLException, H2ZeroPrimaryKeyException, H2ZeroFinderException {
		if(!primaryKeySet()) {
			throw new H2ZeroPrimaryKeyException("Cannot refresh model 'Field' when primary key is null.");
		}

		Field field = FieldFinder.findByPrimaryKeySilent(connection, this.idField);
		if(null == field) {
			throw new H2ZeroFinderException("Could not find the model 'Field' with primaryKey of " + getPrimaryKey());
		}
		this.idField = field.getIdField();
		this.idFieldType = field.getIdFieldType();
		this.idCollection = field.getIdCollection();
		this.nmField = field.getNmField();
		this.Collection = null;
	}

	public static String[] getHitFields() { return(HIT_FIELDS); }
	public static int[] getHitCounts() { return(HIT_COUNTS); }

	/**
	 * Get the hit count for a specific field - look at the <code>public static HIT_*</code>
	 * fields to retrieve a specific field.
	 *
	 * @param hitCountField the hit count field number to retrieve the hit count from
	 *
	 * @return the hit count for the field
	 * 
	 * <p>{@link #HIT_ID_FIELD Use <code>Field.HIT_ID_FIELD</code> to retrieve the hit count for the <code>id_field</code> field}</p>
	 * <p>{@link #HIT_ID_FIELD_TYPE Use <code>Field.HIT_ID_FIELD_TYPE</code> to retrieve the hit count for the <code>id_field_type</code> field}</p>
	 * <p>{@link #HIT_ID_COLLECTION Use <code>Field.HIT_ID_COLLECTION</code> to retrieve the hit count for the <code>id_collection</code> field}</p>
	 * <p>{@link #HIT_NM_FIELD Use <code>Field.HIT_NM_FIELD</code> to retrieve the hit count for the <code>nm_field</code> field}</p>

	 */
	public static int getHitCountForField(int hitCountField) { return(HIT_COUNTS[hitCountField]); }

	public FieldType getFieldType() {
		return(FieldType.ALL_LOOKUP.get(this.idFieldType));
	}

	public Collection getCollection() {
		if(null == this.Collection) {
			this.Collection = CollectionFinder.findByPrimaryKeySilent(this.idCollection);
		}
		return(this.Collection);
	}

	public static void updateHitCount(int offset) {
		HIT_COUNTS[0]++;
		HIT_COUNTS[offset]++;
	}

	/*
	 * Boring ol' getters and setters 
	 * 
	 * On setting any of these fields - the 'isDirty' flag will be set
	 * 
	 */

	public Long getPrimaryKey() { updateHitCount(1); return(this.idField); }
	public void setPrimaryKey(Long idField) { if(isDifferent(this.idField, idField)) { this.idField = idField;this.isDirty = true; }}
	public Long getIdField() { updateHitCount(1); return(this.idField); }
	public void setIdField(Long idField) { if(isDifferent(this.idField, idField)) { this.idField = idField;this.isDirty = true; }}
	public Long getIdFieldType() { updateHitCount(2); return(this.idFieldType); }
	public void setIdFieldType(Long idFieldType) { if(isDifferent(this.idFieldType, idFieldType)) { this.idFieldType = idFieldType;this.isDirty = true; }}
	public Long getIdCollection() { updateHitCount(3); return(this.idCollection); }
	public void setIdCollection(Long idCollection) { if(isDifferent(this.idCollection, idCollection)) { this.idCollection = idCollection;this.isDirty = true; this.Collection = null;}}
	public String getNmField() { updateHitCount(4); return(this.nmField); }
	public void setNmField(String nmField) { if(isDifferent(this.nmField, nmField)) { this.nmField = nmField;this.isDirty = true; }}

	@Override
	public ValidationBean validate() {
		ValidationBean validationBean = new ValidationBean();

		ValidationFieldBean idFieldTypeValidationFieldBean = new BigintValidator("id_field_type", idFieldType.toString(), 0, 0, false).validate();
		idFieldTypeValidationFieldBean.setIsIncorrectForeignKey(!FieldTypeQuestion.internalDoesPrimaryKeyExist(idFieldType));
		validationBean.addValidationFieldBean(idFieldTypeValidationFieldBean);

		ValidationFieldBean idCollectionValidationFieldBean = new BigintValidator("id_collection", idCollection.toString(), 0, 0, false).validate();
		idCollectionValidationFieldBean.setIsIncorrectForeignKey(!CollectionQuestion.internalDoesPrimaryKeyExist(idCollection));
		validationBean.addValidationFieldBean(idCollectionValidationFieldBean);

		validationBean.addValidationFieldBean(new VarcharValidator("nm_field", nmField.toString(), 0, 256, false).validate());
		return(validationBean);
	}


	@Override
	public String toString() {
		return(
			"{\"Field\": {" +
			"\"idField\":\"" + this.idField + "\"" +
			"\"idFieldType\":\"" + this.idFieldType + "\"" +
			"\"idCollection\":\"" + this.idCollection + "\"" +
			"\"nmField\":\"" + this.nmField + "\"" +
			"}");
	}
	public JSONObject getToJSON() {
		return(toJSON());
	}

	public JSONObject toJSON() {
		JSONObject jsonObject = new JSONObject();

		jsonObject.put("type", "table");
		jsonObject.put("name", "Field");
		JSONObject fieldsObject = new JSONObject();

		ModelBaseHelper.addtoJSONObject(fieldsObject, "idField", this.getIdField());
		ModelBaseHelper.addtoJSONObject(fieldsObject, "idFieldType", this.getIdFieldType());
		ModelBaseHelper.addtoJSONObject(fieldsObject, "idCollection", this.getIdCollection());
		ModelBaseHelper.addtoJSONObject(fieldsObject, "nmField", this.getNmField());

		jsonObject.put("fields", fieldsObject);

		return(jsonObject);
	}


	public String toJsonString() {
		return(toJSON().toString());
	}

	public String getJsonString() {
		return(toJsonString());
	}

	/**
	 * <p>Return an XML representation of the <code>Field</code> model as a <code>String</code>, 
	 * with the root node being the name of the table - i.e. <code>&lt;field /&gt;</code> 
	 * and the child nodes the name of the fields.</p>
	 * 
	 * <p><strong>NOTE:</strong> Any field marked as secure will not be included as
	 * part of the XML document</p>
	 * 
	 * @return An XML representation of the model as a <code>String</code>.
	 */
	public String toXMLString() {
		return("<field>" + 
			String.format("<id_field null=\"%b\">%s</id_field>", (this.getIdField() == null), (this.getIdField() != null ? this.getIdField() : "")) + 
			String.format("<id_field_type null=\"%b\">%s</id_field_type>", (this.getIdFieldType() == null), (this.getIdFieldType() != null ? this.getIdFieldType() : "")) + 
			String.format("<id_collection null=\"%b\">%s</id_collection>", (this.getIdCollection() == null), (this.getIdCollection() != null ? this.getIdCollection() : "")) + 
			String.format("<nm_field null=\"%b\">%s</nm_field>", (this.getNmField() == null), (this.getNmField() != null ? XmlHelper.escapeXml(this.getNmField()) : "")) + 
			"</field>");
	}


	/**
	 * Get the hit count statistics as a JSON encoded object as a <code>String</code>.
	 *
	 * @return the JSON Object as a <code>String</code>.
	 */
	public static String getHitCountJson() {
		JSONObject jsonObject = new JSONObject();
		jsonObject.put("type", "Field");
		jsonObject.put("total", HIT_COUNTS[0]);
		jsonObject.put("idField", HIT_COUNTS[1]);
		jsonObject.put("idFieldType", HIT_COUNTS[2]);
		jsonObject.put("idCollection", HIT_COUNTS[3]);
		jsonObject.put("nmField", HIT_COUNTS[4]);
		return(jsonObject.toString());
	}

}