package com.synapticloop.tinycms.sqlite.h2zero;

// - - - - thoughtfully generated by synapticloop h2zero - - - - 
//    with the use of synapticloop templar templating language
//      (java-create-connection-manager-initialise.templar)

import com.synapticloop.h2zero.base.manager.sqlite3.ConnectionManager;

public class ConnectionManagerInitialiser extends ConnectionManager {
	protected static final String CONNECTION_POOL_NAME = "com.synapticloop.tinycms.sqlite.h2zero.tinycms";
}
