package com.synapticloop.tinycms.sqlite.h2zero.model.util;

// - - - - thoughtfully generated by synapticloop h2zero - - - - 
//    with the use of synapticloop templar templating language
//            (java-create-constants.templar)

public class Constants {
	// The binder variables below are used to show up compilation errors where
	// it has been removed from the generation.

	// Model Binder for the collection table
	public static final String COLLECTION_BINDER = "COLLECTION";
	// Model Binder for the field_type table
	public static final String FIELD_TYPE_BINDER = "FIELD_TYPE";
	// Model Binder for the field table
	public static final String FIELD_BINDER = "FIELD";
	// Model Binder for the data_collection table
	public static final String DATA_COLLECTION_BINDER = "DATA_COLLECTION";
	// Model Binder for the data_field table
	public static final String DATA_FIELD_BINDER = "DATA_FIELD";

	// Field constants for the collection table
	public static final String COLLECTION_ID_COLLECTION = "idCollection";
	public static final String COLLECTION_NM_COLLECTION = "nmCollection";


	// Field constants for the field_type table
	public static final String FIELD_TYPE_ID_FIELD_TYPE = "idFieldType";
	public static final String FIELD_TYPE_NM_FIELD_TYPE = "nmFieldType";
	public static final String FIELD_TYPE_FL_FIELD_SHOULD_QUOTE = "flFieldShouldQuote";


	// Field constants for the field table
	public static final String FIELD_ID_FIELD = "idField";
	public static final String FIELD_ID_FIELD_TYPE = "idFieldType";
	public static final String FIELD_ID_COLLECTION = "idCollection";
	public static final String FIELD_NM_FIELD = "nmField";


	// Field constants for the data_collection table
	public static final String DATA_COLLECTION_ID_DATA_COLLECTION = "idDataCollection";
	public static final String DATA_COLLECTION_ID_COLLECTION = "idCollection";
	public static final String DATA_COLLECTION_NM_COLLECTION = "nmCollection";
	public static final String DATA_COLLECTION_FL_IS_PUBLISHED = "flIsPublished";


	// Field constants for the data_field table
	public static final String DATA_FIELD_ID_DATA_FIELD = "idDataField";
	public static final String DATA_FIELD_ID_FIELD = "idField";



}