package com.synapticloop.tinycms.sqlite.h2zero.model.util;

// - - - - thoughtfully generated by synapticloop h2zero - - - - 
//    with the use of synapticloop templar templating language
//            (java-create-model-statistics.templar)

import com.synapticloop.tinycms.sqlite.h2zero.model.Collection;
import com.synapticloop.tinycms.sqlite.h2zero.model.Field;
import com.synapticloop.tinycms.sqlite.h2zero.model.DataCollection;
import com.synapticloop.tinycms.sqlite.h2zero.model.DataField;

import java.lang.StringBuilder;

public class Statistics {
	public static String getHitCountJson() {
		return("[" +
			Collection.getHitCountJson() +
			", " +
			Field.getHitCountJson() +
			", " +
			DataCollection.getHitCountJson() +
			", " +
			DataField.getHitCountJson() +
		"]");
	}
}